### ISSUE TITLE
Concern: Warning! Disk size is smaller than the main header indicates! 

### ISSUE THREAD

**Issue by NotDarkn** [CoolElectronics/sh1mmer.me#103]
**OS/Distro:**
EndeavourOS w/ GNOME 45.1

**Issue:**
Using `wax_legacy.sh` with JACUZZI prevents the error "Warning! Disk size is smaller than the main header indicates!"

**Description:**
When I use the latest version of `wax_legacy.sh` on an RMA shim such as JACUZZI, the finishing stage presents the error "Warning! Disk size is smaller than the main header indicates!". This doesn't affect the injected shim from building built and used, however it is a bit of a concerning error considering this wasn't here in previous versions.

**Log:**
```
Info: Mounting SH1MMER
Info: Injecting payload (2/2)
Info: Truncating image to 329MiB
Warning! Disk size is smaller than the main header indicates! Loading
secondary header from the last sector of the disk! You should use 'v' to
verify disk integrity, and perhaps options on the experts' menu to repair
the disk.
Caution: invalid backup GPT header, but valid main header; regenerating
backup header from main header.

Warning! Error 25 reading partition table for CRC check!
Warning! One or more CRCs don't match. You should repair the disk!
Main header: OK
Backup header: ERROR
Main partition table: OK
Backup partition table: ERROR

****************************************************************************
Caution: Found protective or hybrid MBR and corrupt GPT. Using GPT, but disk
verification and recovery are STRONGLY recommended.
****************************************************************************
Warning: The kernel is still using the old partition table.
The new table will be used at the next reboot or after you
run partprobe(8) or kpartx(8)
The operation has completed successfully.
Info: Done. Have fun!
```

**Notes:**
- Yes, I have all of the dependencies.
- No, I have not tried another RMA shim.
- This is on a new install of EndeavourOS.
- This was tested on both an MBR & GPT install.
- This was forked from the currently latest commit, [f4bb41d](https://github.com/MercuryWorkshop/sh1mmer/commit/f4bb41d87a8a049646ce3323f43dc311d66a58e3)

**Comment by velzie** [comment]
obly b

**Comment by BinBashBanana** [comment]
this is intended
