### ISSUE TITLE
Sh1mmer not booting on Lenovo 100e Chromebook Gen 4 (Corsola)

### ISSUE THREAD

**Issue by ghost** [CoolElectronics/sh1mmer.me#107]
I downloaded the Corsola RMA Shim from both [dl.osu.bio](https://dl.osu.bio/) and [chrome100.dev](https://chrome100.dev/board/corsola/) and tried both [Wax4Web](https://osu.bio/sh1mmer/builder) and Wax4Windows to inject Sh1mmer into the shim. I then used the Chromebook Recovery Utility to write onto the USB drive. I pressed Esc + Refresh + Power, Ctrl + D, Enter, Esc + Refresh + Power again, and plugged the USB drive into the laptop, but instead of booting into Sh1mmer, I get an error saying "No valid image detected" "Make sure your external disk has a valid recovery image, and re-insert the disk when ready." I tried shims from both dl.osu.bio and chrome100.dev, but they both don't work. I also tried 2 more different USB drives, but it was to no avail. Has Google patched this, or is it due to Corsola or it being an ARM Chromebook?

**Comment by grandpa1946** [comment]
what version are you on? make sure to read the [readme](https://github.com/MercuryWorkshop/sh1mmer/blob/beautifulworld/README.md#the-fog)

**Comment by NotDarkn** [comment]
> what version are you on? make sure to read the [readme](https://github.com/MercuryWorkshop/sh1mmer/blob/beautifulworld/README.md#the-fog)

SH1mmer can boot on any version, v112, v114, v117, etc, it doesn't matter. This is more likely to be a USER issue rather than an issue on CrOS or SH1mmer.

**Comment by grandpa1946** [comment]
> > what version are you on? make sure to read the [readme](https://github.com/MercuryWorkshop/sh1mmer/blob/beautifulworld/README.md#the-fog)
> 
> SH1mmer can boot on any version, v112, v114, v117, etc, it doesn't matter. This is more likely to be a USER issue rather than an issue on CrOS or SH1mmer.

I thought it was a fw-update related problem...

**Comment by NotDarkn** [comment]
> > > what version are you on? make sure to read the [readme](https://github.com/MercuryWorkshop/sh1mmer/blob/beautifulworld/README.md#the-fog)
> > 
> > 
> > SH1mmer can boot on any version, v112, v114, v117, etc, it doesn't matter. This is more likely to be a USER issue rather than an issue on CrOS or SH1mmer.
> 
> I thought it was a fw-update related problem...

That's for when SH1mmer fails, not booting.

**Comment by Xoui** [comment]
Google hasnt patched it *JUST WAIT FOR A SECOND* like u can have an injected shim and then boot up. the only PATCH google has done is if you have upgraded/updated throught 112 and it wont work. You have to use fog.gay

**Comment by r58Playz** [comment]
This is user error, shims still boot on the latest firmware version.
