### ISSUE TITLE
Conflicting licensing

### ISSUE THREAD

**Issue by Neetpone** [CoolElectronics/sh1mmer.me#111]
On your page: https://sh1mmer.me/scam you state things such as
> Any kind of sale, bundling, or redistribution in association with commercial activity is strictly forbidden and a violation of copyright. 

and

> Keep in mind that this kind of sale is illegal (selling our free software is a violation of copyright) and also fraudulent.

However, your project is licensed under the GPL, which does not prohibit, and in fact explicitly *permits* commercial use and sale. So... which is it?

**Comment by ading2210** [comment]
The original authors of this repo consider these statements a "joke" and "not legal advice." 

Unfortunately that's not how software licensing works, but they disagree. Obviously you can't just say that something *people have the right to do under the GPL* is illegal, however they clearly have no interest in fixing this seeing how PR #112 was closed.

**Comment by velzie** [comment]
as it clearly says it isn't legal advice and doesn't matter.
