### ISSUE TITLE
Write protection disabling does not work

### ISSUE THREAD

**Issue by RintaDev5792** [CoolElectronics/sh1mmer.me#113]
I'm on a Chromebook with the CR50 write protection, but unplugging the big battery and booting it still says that write protection is enabled and can't do anything.

**Comment by RintaDev5792** [comment]
I am so sorry I am on too new of a version I think (my school blocked chrome://version)

**Comment by leahanderson1** [comment]
your chromebook has been tsunami'd, sh1mmering is impossible unless you do the pencil method.

**Comment by RintaDev5792** [comment]
What's the pencil method?

**Comment by NotDarkn** [comment]
> What's the pencil method?

https://blog.osu.bio/blog/the-tsunami#bypassing-instructions
