### ISSUE TITLE
possible bypass idea??

### ISSUE THREAD

**Issue by mostwise** [CoolElectronics/sh1mmer.me#114]
so, i am very new to the chromeOS hacking scene, and i have a few questions and possible ideas.

so one of my ideas is that maybe we could trigger some crash or corruption in the OS to be able to downgrade because the OS can't continue if it is corrupted. one thing preventing this is that there might be some sort of firmware to remember the OS version and only use versions such as 117 (for example)

one question though, is there public source for chromeOS or chromiumOS??

**Comment by leahanderson1** [comment]
https://chromium.googlesource.com/chromiumos/docs/+/HEAD/developer_guide.md

**Comment by r58Playz** [comment]
> so one of my ideas is that maybe we could trigger some crash or corruption in the OS to be able to downgrade because the OS can't continue if it is corrupted. one thing preventing this is that there might be some sort of firmware to remember the OS version and only use versions such as 117 (for example)

This is not possible.

> one question though, is there public source for chromeOS or chromiumOS??

https://source.chromium.org/
