### ISSUE TITLE
no package managers/installers in bash shell

### ISSUE THREAD

**Issue by sosdos** [CoolElectronics/sh1mmer.me#119]
apt, apt-get, dpkg, pkg aren't there, leaving me with no way to install anything

trying to install firefox again, since the version installed doesn't start in weston. 

sorry in advance if I wasn't supposed to make this issue

**Comment by ZeglolTheThirtySixth** [comment]
Firefox is already there; there just isn't a configuration file for weston, so it won't show up in the launcher and X11 isn't started so it won't work even if you manually launch it from the terminal. A large sum of packages provided by Chromebrew are mounted over /usr/local in devshims, so most packages you'll need are already there. You should read weston's documentation if you try to set it up. However, projects like Shimboot and TerraOS allow you to boot linux on a shim and have package managers and desktop environments fully configured and built for you, so I personally recommend you use one of those.

**Comment by TheMemeSniper** [comment]
intended, use terraOS or shimboot if you need a linux system

**Comment by sosdos** [comment]
okay, thanks.

just tried terraOS and it works great
