### ISSUE TITLE
Ubuntu won't boot and I am having to factory reset the device after leaving SH1mmer menu

### ISSUE THREAD

**Issue by FunnyCorgi** [CoolElectronics/sh1mmer.me#130]
Whenever I use the SH1mmer menu to enable usb booting, it succeeds. However, when I leave the menu with the restart into ChromeOS option, it forces me into the "OS verification is off. Press enter to enable and clear local data. To go back, press ESC."
When I press ESC, nothing happens, and I can only enable OS verification, and then it clears. I tried this twice on my school device, and it gives the same result.

**Comment by FunnyCorgi** [comment]
Basically, I can't enter back into verified mode on my system.

**Comment by FunnyCorgi** [comment]
Meaning I can't shutdown the device(well I can, but when it starts it goes straight to recov. screen).

And even then I have the same problem with the esc key.

**Comment by NotDarkn** [comment]
literally just press `CTRL + D` on that screen, also this isn't an issue with SH1mmer, rather it's an issue with your incompetence

**Comment by FunnyCorgi** [comment]
sorry I experimented with that a few years ago, and forgot. Thank you!

BTW I wasn't trying to say it was an issue with SH1mmer
