### ISSUE TITLE
Doesn't work: pressing `CTRL + D` on os verification off screen after reboot from SH1mmer,

### ISSUE THREAD

**Issue by FunnyCorgi** [CoolElectronics/sh1mmer.me#132]
literally just press `CTRL + D` on that screen, also this isn't an issue with SH1mmer, rather it's an issue with your incompetence

_Originally posted by @NotDarkn in https://github.com/MercuryWorkshop/sh1mmer/issues/130#issuecomment-2081222551_
            

This didn't work.
I have a lenovo 300e 2nd gen chromebook and chromeos
118.0.5993.164 (Official Build)

(btw I am making a new issue because idk how github notifications work for issues.)

**Comment by FunnyCorgi** [comment]
If you can't fix this, thats ok, I will try E-Halcyon too and see if that works.

**Comment by FunnyCorgi** [comment]
Actually I might try cryptosmite first.


Which do you think is safer?

**Comment by FunnyCorgi** [comment]
I don't want to risk bricking my chromebook

**Comment by NotDarkn** [comment]
idk if you know this or not but **SH1MMER doesn't work on v118.** you **HAVE TO** use CryptoSmite instead.

**Comment by FunnyCorgi** [comment]
sorry, I'll try that. I didn't realize.

**Comment by FunnyCorgi** [comment]
Just one question: will fakemurk work with this?

**Comment by r58Playz** [comment]
Fakemurk is unmaintained. It is not guaranteed to work.
