### ISSUE TITLE
HWID change feature request

### ISSUE THREAD

**Issue by PeapGit** [CoolElectronics/sh1mmer.me#142]
After 125 new mitigations have come out which makes it even harder to unenroll completely. One of these makes chromebooks check for enrollment even if tpm doesn't have enrollment on it. This means that the only way to unenroll completely anymore is to change HWID. Can you add a payload which will change HWID for those who have WP off and want to unenroll completely 125+.

**Comment by velzie** [comment]
hwid has nothing to do with enrollment and the rest of your statement is also completely wrong
