### ISSUE TITLE
a bit unclear how to boot with usbs?

### ISSUE THREAD

**Issue by TheTruePerson** [CoolElectronics/sh1mmer.me#149]
I booted Sh1mmer and I used the option to enable booting USBs, and now I have a bootable USB with ChromeOS. My computer, however, keeps on trying to recover the computer instead of booting into the USB. Its probably not a sh1mmer problem, just that i'm not doing it right... so maybe specify how to boot USBs after you enable them?

**Comment by BinBashBanana** [comment]
This is not a sh1mmer issue
