### ISSUE TITLE
another issue 

### ISSUE THREAD

**Issue by vernal-ria0** [CoolElectronics/sh1mmer.me#15]
sorry to need help again but on this code sudo sh wax.sh /path/to/the/shim/you/downloaded.bin is says cant open wax.sh

**Comment by velzie** [comment]
💀

**Comment by velzie** [comment]
did you... download it

**Comment by vernal-ria0** [comment]
yes I download the bin and all the packages

**Comment by vernal-ria0** [comment]
could I be cause it is not on my windows drive and is on my data d

**Comment by vernal-ria0** [comment]
i installed all the packages. are you talking about the shim I do have it but not on my windows drive. is that the problem

**Comment by amelia-bartlett** [comment]
> i installed all the packages. are you talking about the shim I do have it but not on my windows drive. is that the problem

Honestly, it sounds like the problem is that you are unable to wrap your head around the concept that `wax.sh` is not designed to run on a Windows NT or DOS kernel.
