### ISSUE TITLE
ive downloaded everything

### ISSUE THREAD

**Issue by vernal-ria0** [CoolElectronics/sh1mmer.me#16]
i have installed all packages and have a shim but says cant open wax.sh

**Comment by velzie** [comment]
Issues are not for tech support!!! They are for problems with the program itself. Please stop spamming the project with them and learn a thing or 2 about linux.

**Comment by amelia-bartlett** [comment]
![image](https://user-images.githubusercontent.com/44680463/219642888-92eb5ee2-68f4-433c-b235-1a6e2f40c650.png)
