### ISSUE TITLE
dl.sh1mmer.me down

### ISSUE THREAD

**Issue by grandpa1946** [CoolElectronics/sh1mmer.me#18]
![image](https://user-images.githubusercontent.com/115040432/218102575-caed8b81-78d8-4f9a-add4-68f8655155c5.png)
why is it down? i don't get enough info.

**Comment by TheMemeSniper** [comment]
🐟

**Comment by grandpa1946** [comment]
this isn't completed, 🐟 ain't gonna do it

**Comment by velzie** [comment]
fish emoji

**Comment by velzie** [comment]
in all seriousness the site is down because the sharepoint token expired and rafflesia won't be able to update it for a week or 2
just use the web builder for now, or the bw-minimal branch which doesn't require chromebrew

**Comment by amelia-bartlett** [comment]
afaik the site is not needed, you should still be able to build locally with the shell script

**Comment by grandpa1946** [comment]
shell script?

**Comment by TheMemeSniper** [comment]
🐟

**Comment by velzie** [comment]
up

**Comment by grandpa1946** [comment]
let's goo!

**Comment by ghost** [comment]
get the shims from the the mirror dl.osu.bio
