### ISSUE TITLE
where to download shim for lenovo chromebook 300e gen 2 ast

### ISSUE THREAD

**Issue by ghost** [CoolElectronics/sh1mmer.me#21]
i need the shim image to flash to a usb, i am not an authorized lenovo repair so i can't get it, and it's not on the driver site, i need it to remove enrollment

and no i am not underage lol

**Comment by velzie** [comment]
1. you are underage
2. read the instructions

**Comment by CoolElectronics** [comment]
1. you are underage
2. read the instructions

**Comment by CoolElectronics** [comment]
1. you are underage
2. read the instructions

**Comment by TheMemeSniper** [comment]
https://user-images.githubusercontent.com/67394719/218538840-9f55b94f-081b-4a1c-8068-0f6be0407c8f.mp4

**Comment by ghost** [comment]
No I'm just an idiot that didn't realize

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by grandpa1946** [comment]
https://lenovo-driver-download.com/driver/300E-CHROMEBOOK-2ND-GEN-AST
