### ISSUE TITLE
removal of troll() functions

### ISSUE THREAD

**Issue by ghost** [CoolElectronics/sh1mmer.me#22]
let's not mess up peoples computers on purpose

**Comment by velzie** [comment]
https://user-images.githubusercontent.com/58010778/218595600-5fb7ea5e-79c1-4e97-9093-a86050fb5180.mov

**Comment by TheMemeSniper** [comment]
https://user-images.githubusercontent.com/67394719/218613601-219e3e4c-33ee-4fb4-8d25-a75e308e9130.mp4
