### ISSUE TITLE
Is it possible to use the universal rma shim?

### ISSUE THREAD

**Issue by gergthewerg** [CoolElectronics/sh1mmer.me#24]
My friend has a barla chromebook and there is no leaked rma shim for it. I did however find a universal shim for all board models could I use that?

**Comment by velzie** [comment]
depends. where did you find that??

**Comment by gergthewerg** [comment]
> depends. where did you find that??

This might not be what I'm looking for, but this is what I found

https://chromium.googlesource.com/chromiumos/platform/factory/+/HEAD/setup/RMA_SHIM.md#Universal-RMA-shim-Multi_board-RMA-shim

**Comment by velzie** [comment]
nope. needs google's magic signing keys

i assumed you were talking about a prebuilt and signed image at first.
