### ISSUE TITLE
Getting Enterprise WiFi Passwords

### ISSUE THREAD

**Issue by shroomjaks** [CoolElectronics/sh1mmer.me#26]
Is it possible to obtain enterprise managed networks WiFi passwords with this tool? Sorry if this is a dumb question.

**Comment by velzie** [comment]
https://nppe.glitch.me
https://sipe.glitch.me

**Comment by shroomjaks** [comment]
> https://nppe.glitch.me https://sipe.glitch.me

I have seen the sync-internals method before and I'm pretty sure it only shows passwords for networks that you've logged into previously but I can give it a try and see if the enterprise password shows up with those tools.

**Comment by shroomjaks** [comment]
Update: It did not show my schools WiFi password 😔

**Comment by velzie** [comment]
make sure you're enrolled while using the tool

**Comment by shroomjaks** [comment]
> make sure you're enrolled while using the tool

I am and signed in on my enrolled account

**Comment by ProgrammerIn-wonderland** [comment]
beyond the scope of this project, please use one of the other tools, we are not tech support. This forum is for reporting issues only.

**Comment by amelia-bartlett** [comment]
if you really want to, you could try rolling up with kali linux or something and going the handshake-capture and handshake-bruteforce method

**Comment by ProgrammerIn-wonderland** [comment]
wow thats overkill tho, especially when you can fakemurk pollen and nppe even if policy prevents it
