### ISSUE TITLE
If you install MrChromebox's UEFI but then go back to the stock chromebook firmware, can you still re-enroll?

### ISSUE THREAD

**Issue by Lost-Entrepreneur439** [CoolElectronics/sh1mmer.me#28]
If you installed MrChromebox's UEFI on a chromebook that had been un-enrolled with sh1mmer, but then changed your mind, went back to stock firmware, would you still be able to re-enroll the Chromebook or at that point would it be permanently unenrolled?

apologizes if this is a dumb question

**Comment by TheMemeSniper** [comment]
yes, we're not tech support.
