### ISSUE TITLE
fdisk error

### ISSUE THREAD

**Issue by ghost** [CoolElectronics/sh1mmer.me#30]
I went into the code after several errors claimng 'fdisk not found'. I am not a fully advanced shell developer, but I do know that fdisk is deprecated and needs replacement.

**Comment by ghost** [comment]
NOTE: I am on a sh1mmed chromebook, I'm just making a shim with my custom assets. It does have linux enabled, and I would like ti know if there is a possible workaround.

**Comment by velzie** [comment]
fdisk is fine, it comes preinstalled with almost every single linux distro and that should include cros.
are you sure you ran it as root??
if all else fails, download chromebrew and install the deps that way, but chrome os 100% does come with fdisk, at least on modern versions.

**Comment by ghost** [comment]
alr, ty ill look into it

**Comment by ghost** [comment]
I looked into it, fdisk is not included with crostini. sudo apt install fdisk didn't install the right service, and I do not know what to do. Is there a certain fdisk file I need?
going through your past comment, I did everything correctly.

I used sudo su to run as root
I installed fdisk with sudo apt install fdisk (didn't work, opened an fdisk menu instead of automatically partitioning)

I don't know how to install the dependencies, I am still a learning programmer, and only got into bash right as sh1mmer was found.
If you could put a command to add the chromebrew dev dependencies, it would be incredibly helpful. Thank you!

**Comment by velzie** [comment]
generally you're supposed to use crosh shell, not crostini although there's no reason it wouldn't work in crostini

not sure why you can't install fdisk but that falls under "tech support"

**Comment by ghost** [comment]
I installed fdisk just fine, it just wasn't the right thing. 
It pulled up a menu that said:
fdisk created by (random user)
partition header: |

**Comment by velzie** [comment]
what's the output of fdisk --v

**Comment by ProgrammerIn-wonderland** [comment]
> I went into the code after several errors claimng 'fdisk not found'. I am not a fully advanced shell developer, but I do know that fdisk is deprecated and needs replacement.

fdisk is...  Not deprecated that's for sure

**Comment by ghost** [comment]
nothing happened, skipped to loop device but it failed 
i dont have the exact details but it said something among the lines of "couldn't create loop device: error"

**Comment by velzie** [comment]
are you root

**Comment by ghost** [comment]
yes

**Comment by velzie** [comment]
full error message please

**Comment by ProgrammerIn-wonderland** [comment]
Screenshots would also be nice, also try sudo apt install fdisk

**Comment by ghost** [comment]
i tried install fdisk, didnt work. I'll reinstall the shim and repeat the process and send screenshots.

**Comment by ProgrammerIn-wonderland** [comment]
Wdym by reinstall the shim?

**Comment by ProgrammerIn-wonderland** [comment]
Also could you send a pic of fdisk failing to install

**Comment by ghost** [comment]
the process has to be reinstalled because it modifies the sh1m file and has to be reinstalled in the event it fails

**Comment by ProgrammerIn-wonderland** [comment]
Well if loop failed to mount and fdisk failed to.. fdisk, the image wasn't modified

**Comment by velzie** [comment]
> (didn't work, opened an fdisk menu instead of automatically partitioning)

it's supposed to do that. wait

**Comment by ProgrammerIn-wonderland** [comment]
Oh yeah it pauses on the fdisk menu for a bit, while it's partitioning, it's not of any concern, that's intended behavior. The slower your Chromebook the longer it'll take

**Comment by ghost** [comment]
oh, okay. Thank you!

**Comment by ghost** [comment]
loop device isnt working now, I have screenshots. I followed instructions as I was told
![Screenshot 2023-02-18 8 58 07 PM](https://user-images.githubusercontent.com/95651912/219908067-25d06ba0-e5ee-4025-b42a-21bc3815102d.png)

**Comment by velzie** [comment]
do we add crostini to the list of unsupported devices

also you run it with bash not sh

**Comment by ghost** [comment]
would running as bash make a difference

**Comment by velzie** [comment]
uh yeah there are errors earlier on because of it

**Comment by ghost** [comment]
![Screenshot 2023-02-18 9 42 08 PM](https://user-images.githubusercontent.com/95651912/219909269-79b068e8-fb77-4e93-b1ec-ea5d4b13fa5f.png)
didnt work

**Comment by ghost** [comment]
I think its safe to say crostini is unsupported

**Comment by ghost** [comment]
is it possible to make a loop device workaround

**Comment by velzie** [comment]
no
will add crostini to the list
