### ISSUE TITLE
scam.html, scam.md et cetera make inaccurate claims about the GPL 3

### ISSUE THREAD

**Issue by amelia-bartlett** [CoolElectronics/sh1mmer.me#31]
I saw your increased anxiety about "scams" and felt that I had to weigh in (I have also been inspired by the copyright disclaimer of Team Twiizers with some of my own software, and have made the same legal mistake myself).

Before claiming that distributing the software for a fee is a violation of its copyright, you should seriously read:
https://www.gnu.org/licenses/gpl-faq.en.html#DoesTheGPLAllowMoney

It would only be illegal if they made a profit on the distribution of _source code_ of the project when requested (after a binary copy is obtained)

Should you still wish to prohibit this form of distribution, then you should seek a new, proprietary software license (you will, of course, need unanimous agreement from anyone who wrote a portion of the code, since you can't just relicense copyrighted material where someone else holds the copyright where the license does not allow that - that _would_ be copyright infringement, and the GPL 3 does of course require all derivative works to be redistributed under the same license).

**Comment by ProgrammerIn-wonderland** [comment]
I mean, scam.md isn't meant to be an actual warning but rather a funny reference to hackmii's warning tbh. I might add a joke disclaimer at the bottom

**Comment by TheMemeSniper** [comment]
fixed in commit ae73e42
