### ISSUE TITLE
shim mirror down

### ISSUE THREAD

**Issue by Merlinxx10** [CoolElectronics/sh1mmer.me#32]
I apologize as I do think this is included in your whole do not make a issue if the following thing but I am not able to access and download the Shim matching my board I get this message "No webpage was found for the web address: https://mirror.the-repo.org/RMA/Shims/grunt.bin HTTP ERROR 404" regardless the device I use I get the same message and I genuinely don't know where else to go about this or else I would have went there first. Is there just no way to access the files anymore or are they just down or something?

**Comment by velzie** [comment]
reaaaad the directions i swear
https://files.ultimatesrv.com/

**Comment by velzie** [comment]
ah ok uh i messed up no the server is actually down uhhhhh wait like a few hours

**Comment by TheMemeSniper** [comment]
read the pinned issue, marking as wontfix


https://user-images.githubusercontent.com/67394719/220801408-2f86da5a-954e-4cba-b4fb-cacba0ae8129.mp4

**Comment by TheMemeSniper** [comment]
we will still provide status updates for you

**Comment by Merlinxx10** [comment]
Thank you so much for not smiting me but in all seriousness, I do apologize again that I had to submit wouldn't have done it if there was another place for me to go

**Comment by amelia-bartlett** [comment]
> I apologize as I do think this is included in your whole do not make a issue if the following thing but I am not able to access and download the Shim matching my board I get this message "No webpage was found for the web address: https://mirror.the-repo.org/RMA/Shims/grunt.bin HTTP ERROR 404" regardless the device I use I get the same message and I genuinely don't know where else to go about this or else I would have went there first. Is there just no way to access the files anymore or are they just down or something?

your link works for me

**Comment by amelia-bartlett** [comment]
> > I apologize as I do think this is included in your whole do not make a issue if the following thing but I am not able to access and download the Shim matching my board I get this message "No webpage was found for the web address: https://mirror.the-repo.org/RMA/Shims/grunt.bin HTTP ERROR 404" regardless the device I use I get the same message and I genuinely don't know where else to go about this or else I would have went there first. Is there just no way to access the files anymore or are they just down or something?
> 
> your link works for me

oops, didn't see the other stuff you wrote, sorry!

**Comment by velzie** [comment]
yes, mirror is back up
