### ISSUE TITLE
Support Tool

### ISSUE THREAD

**Issue by Woosh9129** [CoolElectronics/sh1mmer.me#33]
wax.sh: line 98: syntax error: unexpected end of file

There is no line 98 in wax.sh though as I downloaded it as well, please help.

**Comment by Woosh9129** [comment]
Fixed. Instead of being a skid, I recoded the wax script

**Comment by amelia-bartlett** [comment]
> Fixed. Instead of being a skid, I recoded the wax script

you mind posting a link to your fixed script, for everyone else?

or even filing a pr?

**Comment by amelia-bartlett** [comment]
that said, I had the same issue (I was trying to rewrite wax.sh to use whiptail).

To fix it, just delete the newline at the end, then replace it.  (I think its an incorrect line ending or something)
