### ISSUE TITLE
Chromebook not unenrolling

### ISSUE THREAD

**Issue by just-some-random-kid-in-school** [CoolElectronics/sh1mmer.me#39]
/usr/sbin/sh1mmer_utilities.sh: line 73: read: THERE WAS AN ERROR! The utility likely did not work. Press return to continue. ' : not a valid identifier

**Comment by just-some-random-kid-in-school** [comment]
Oh yeah also I am slightly retarded so sorry if there is an obvious solution

**Comment by velzie** [comment]
https://www.reddit.com/r/MercuryWorkshop/comments/11ohd7m/how_to_use_sh1mmer_after_chrome_111/

**Comment by ghost** [comment]
downgrade to v110 using a recovery image from chrome100.dev
