### ISSUE TITLE
firmware_management_parameters cannot remove

### ISSUE THREAD

**Issue by ODog235** [CoolElectronics/sh1mmer.me#42]
Wipe flags and unblock dev_mode fail.

**Comment by TheMemeSniper** [comment]
this is due to the new v111 update, as for if we will fix this (or be able to at all) we're not sure

**Comment by ODog235** [comment]
Could I downgrade and still use it?

**Comment by TheMemeSniper** [comment]
we're not sure

**Comment by ODog235** [comment]
If it does work, could I stop it from updating if /when I shut it down?

**Comment by ODog235** [comment]
Ok it’s not working, I had dev mode I just wanted to show a friend how to do it and now I can’t do it anymore.

**Comment by TheMemeSniper** [comment]
run `sudo dd if=/dev/zero of=/dev/mmcblk0p5` to destroy the update partition then you can reboot

**Comment by velzie** [comment]
known issue on r111, a "patch" from google

downgrade to r110 or below (chrome100.dev) and rerun shimmer. it will say it fails but work anyway

**Comment by ODog235** [comment]
I downgraded to v91 and it says "dev mode is disabled by system policy" I ran disable block dev mode

**Comment by ODog235** [comment]
https://www.reddit.com/r/MercuryWorkshop/comments/11ohd7m/how_to_use_sh1mmer_after_chrome_111/
Used this guide, it still fails to disable dev mode (I used an v91 image from chrome100.dev but that shouldn't matter)
