### ISSUE TITLE
Used this guide to sh1mmer after v111, it still fails to disable dev mode 

### ISSUE THREAD

**Issue by ODog235** [CoolElectronics/sh1mmer.me#44]
https://www.reddit.com/r/MercuryWorkshop/comments/11ohd7m/how_to_use_sh1mmer_after_chrome_111/
Used this guide, it still fails to disable dev mode (I used an v91 image from chrome100.dev but that shouldn't matter)
#42

**Comment by velzie** [comment]
did you read the post? it unblocks devmode after logging in
