### ISSUE TITLE
I found another way to find device version.

### ISSUE THREAD

**Issue by FancyBoiL1** [CoolElectronics/sh1mmer.me#45]
>If chrome://version is blocked, you can search up your chromebook's model name on chrome100.dev and see what board it corresponds to. 

You can just go to settings and then, apps then google play store, then Manage Android Preferences, and the version will be right at the bottom.

**Comment by TheMemeSniper** [comment]
https://user-images.githubusercontent.com/67394719/228999627-d5f20c94-e0e4-48fb-9a8f-c798b73603f4.mp4

**Comment by FancyBoiL1** [comment]
I wasn't trolling. But ok.

**Comment by TheMemeSniper** [comment]
make a pr, issues aren't the place for this
