### ISSUE TITLE
Something cool I found in chromeOS settings

### ISSUE THREAD

**Issue by ghost** [CoolElectronics/sh1mmer.me#47]
Hello!
So if you go to chrome://os-settings/apps, go to google play, then go to manage android preferences you can see the version name at the bottom of the window that pops up, also im pretty sure it's not blocked for people yet.
I hope you can use this info to help with your stuff.
Thank you!

**Comment by TheMemeSniper** [comment]
🐟

**Comment by TheMemeSniper** [comment]
this is a carbon copy of #45

**Comment by TheMemeSniper** [comment]
also your account has the same guy from #45 following and contributing to your only repo. alt much?

**Comment by ghost** [comment]
no I am not, I am a friend of him though, I just thought that what he found was cool and thought that you could use this. Also why would I contribute to my own repo on a diff account?

**Comment by TheMemeSniper** [comment]
make a pr 🐟🐟🐟🐟🐟🐟🐟🐟🐟🐟🐟🐟🐟🐟🐟🐟🐟🐟🐟🐟🐟🐟

**Comment by ghost** [comment]
whats a pr?

**Comment by TheMemeSniper** [comment]
pull request

**Comment by ghost** [comment]
Ah ok, though may I ask a pull request of what?

**Comment by ghost** [comment]
my repo?
