### ISSUE TITLE
No Payloads?

### ISSUE THREAD

**Issue by kxtzownsu** [CoolElectronics/sh1mmer.me#50]
I tried writing my modified shim multiple times to multiple USB's & SD Cards, and rebuild many times. Every single time I have not been able to use any payloads.
Board: grunt & jacuzzi (tested on both)
Version: jacuzzi: 91.0.4472.102, grunt: 101.0.4951.59

**Comment by velzie** [comment]
read the readme please, you can't get payloads unless you build from source

**Comment by kxtzownsu** [comment]
I did build from source.

**Comment by velzie** [comment]
by "build from source" do you mean you used the web builder? because that isn't the same as manually building from source

**Comment by kxtzownsu** [comment]
No, manually building from source.

**Comment by velzie** [comment]
can you provide a better description of what "not been able to use any payloads" means

**Comment by kxtzownsu** [comment]
No payloads are showing up in the payloads menu when I enter the menu?

**Comment by velzie** [comment]
did you unplug the usb at any point? is there error text while starting?

**Comment by kxtzownsu** [comment]
Nope, none at all.

**Comment by idk-pixel** [comment]
did you use the dev chrome brew and the flag?

**Comment by velzie** [comment]
yeah i may have forgotten to mention but chromebrew flag installs the payloads too
