### ISSUE TITLE
stuck on the device owner has disabled developer mode the system will reboot in verified mode

### ISSUE THREAD

**Issue by chippyhawk** [CoolElectronics/sh1mmer.me#52]
i'm pretty sure this means it's bricked

**Comment by TheMemeSniper** [comment]
wipe GBB flags in sh1mmer

**Comment by velzie** [comment]
go back into verified then??

**Comment by ghost** [comment]
try going back into verified and recovering, then rebuilding sh1mmer
if this doesnt work idk what to tell ya man srry

**Comment by velzie** [comment]
either way not a sh1mmer isssue, closing
