### ISSUE TITLE
unblock_devmode not working

### ISSUE THREAD

**Issue by Acecypress** [CoolElectronics/sh1mmer.me#53]
every time I use unblock_devmode I get an error, and I never am able to fix it. It displays something about line 73, but the error never stays on screen long enough for me to see.

**Comment by Acecypress** [comment]
full error says: "line 73: read: THERE WAS AN ERROR! The utility likely did not work. Press return to continue. ': not a valid identifier"


what should I do?

**Comment by ghost** [comment]
What did you build the shim with?
There may have been an error, try providing more device information,
such as:
- What you built it with (VM, web builder, linux, WSL, etc)
- How old the device is (Damage may occur by people tampering with it)
- Your board name (Most cases the error is in legacy shims for pre-frecon boards)
- If the flash drive was removed incorrectly, corrupted, or damaged
- If there were any errors during the building process

In the meantime, try some of these methods:

- Recovering your chromebook with recovery media
- Rebuilding the shim
- Getting the code for the utility and executing it in bash
- un-enrolll your device and let it boot through the checking device management process, then try entering developer mode again

Overall, this is most likely a hardware issue, and not a sh1mmer issue.

**Comment by velzie** [comment]
unblocking devmode is not possible post 111. downgrade to a pre 111 version and unenroll normally
