### ISSUE TITLE
SH1mmer does not work

### ISSUE THREAD

**Issue by mikeinteltech** [CoolElectronics/sh1mmer.me#55]
Once I finish everything and the jailbreak is injected, I click restart and then it goes to the "OS Verification" screen. Then I click enter and it reboots and still finds the enterprise enrollment. Any help?

**Comment by mikeinteltech** [comment]
111.0.5563.100 (Official Build)
jacuzzi

**Comment by velzie** [comment]
please read other issues before making a duplicate, thanks
