### ISSUE TITLE
Shim file doesn't work with Chromebook Recovery Utility

### ISSUE THREAD

**Issue by byp4ss3r** [CoolElectronics/sh1mmer.me#56]
Doesn't appear that the chromebook recovery utility can write the shim file. I've tried multiple USB's, am using the correct shim, ran chrome as administrator, nothing works.

It gets stuck at writing, 0% completed.

**Comment by ghost** [comment]
just use etcher lol

**Comment by r58Playz** [comment]
Do we really have to start locking issues due to necrobumping
