### ISSUE TITLE
Chrome Recovery Extension/dd

### ISSUE THREAD

**Issue by ehunt34** [CoolElectronics/sh1mmer.me#6]
If you are going to put the speed bump of having to compile yourself so k12sysadmin doesn't get those files, you might as well put the instructions of how to flash the image to a USB using dd on Linux since the extension isn't supported. Of course most Linux users would know, but just saying.

**Comment by velzie** [comment]
overhauled build instructions anyway
the speedbump is intended for everyone, not just the admins.
