### ISSUE TITLE
Permission Denied

### ISSUE THREAD

**Issue by ben10101010** [CoolElectronics/sh1mmer.me#60]
Hello! I created a legacy shim on a Dedede shim, and when I opened it up, it gave me 

`sh: 1: factory_install.sh: Permission denied`

Any solutions?! I used the GitHub repository to build the shim.

**Comment by velzie** [comment]
may be a board specific issue? odd that this would only show up now. either way, it should be fixed with the latest commit, so pull and try again

**Comment by ben10101010** [comment]
Thanks, I'll inform you the results

**Comment by ben10101010** [comment]
Okay, so it works... But I can't factory reset it without a code and without unblocking the dev mode.
(I'm trying to factory reset because it won't unblock devmode or unenroll)

**Comment by amelia-bartlett** [comment]
> Okay, so it works... But I can't factory reset it without a code and without unblocking the dev mode. (I'm trying to factory reset because it won't unblock devmode or unenroll)

are you sure you built your shim correctly?

this code might be from the RMA server unlock process.  The RMA server unlock scripts never execute on a properly built sh1mmer shim (the code execution is redirected before the RMA server unlock script is called)

**Comment by amelia-bartlett** [comment]
> Okay, so it works... But I can't factory reset it without a code and without unblocking the dev mode. (I'm trying to factory reset because it won't unblock devmode or unenroll)

are you on chromeos 111 or above?

**Comment by ben10101010** [comment]
I think so, but the problem is, it’s going to the default RMA restart which either requires Dev Mode to be enabled or you need an auth code, I was hoping the legacy shim removed that, but no luck.

**Comment by velzie** [comment]
there is no "auth code", that's part of the default unmodified rma shim. that's not a version issue, you didn't build it correctly

**Comment by ben10101010** [comment]
The legacy shim has an option to go straight to factory reset, which is the purpose of the original one. The factory reset requires either dev mode, or an auth code

**Comment by velzie** [comment]
ahhh i see
you'll have to modify factory_install.sh yourself to get around that probably, as that's not a supported mode of operation

**Comment by ben10101010** [comment]
Okay I’ll look at the source later, thanks

**Comment by ben10101010** [comment]
Okay, so apparently, there is a function called is_rsu_required() that checks for dev mode. By switching the return value to 1, I was able to unblock it.

**Comment by ben10101010** [comment]
So, apparently it did not work, but on the other hand I found out that if I factory reset it, it will permanently remove enrollment? Is that true?

**Comment by velzie** [comment]
with write protection turned off, yes
