### ISSUE TITLE
Issues sh1mming chromebooks with cr50 on H1 chip after R111

### ISSUE THREAD

**Issue by M1dnight-ofcl** [CoolElectronics/sh1mmer.me#61]
There is currently an issue with sh1mming chromebooks with cr50. I tried disconnecting the battery but that did not work. It was smooth sailing until the final powerwash in which the system still enterprise enrolls even after entering developer mode through the "verification is off" menu on startup. This may be an issue for many board types but these are the most common with the issue:
```txt
Models:  HP Chromebook 11 G series EE, Lenovo Chromebook 500e
Version: >R108
Board:   Octopus, Dedede
```
Sh1mmer was attempted using step from this post due to normal installation not working:
https://www.reddit.com/r/MercuryWorkshop/comments/13dzgak/how_to_use_sh1mmer_after_version_111/

**Comment by velzie** [comment]
downgrade to 110
