### ISSUE TITLE
Error in downgrading v108

### ISSUE THREAD

**Issue by mmz6** [CoolElectronics/sh1mmer.me#66]
I've tested almost every image for octopus chrome100.dev and when trying to downgrade from it and it always says something like "Chrome Image is Outdated" and show a warning emoji. I tried variations of 102 and 107. I have yet to try out variations of 108 as version 108 with .231 at the end of it (forgot the other numbers) does not work with sh1mmer. Is there any fix to this?

**Comment by TheMemeSniper** [comment]
v108 is a LTS release and is affected by the fog

**Comment by TheMemeSniper** [comment]
see #57
