### ISSUE TITLE
what

### ISSUE THREAD

**Issue by mmz6** [CoolElectronics/sh1mmer.me#67]
Fix for LTS Version Chromebooks

1. Get a downgraded image off https://chrome100.dev (preferably the latest 102 because that's the one that worked for me)
2. Mount it on your USB Drive using Chrome Recovery Utility
3. Get your personal chromebook if you don't have it already and do ESC + Refresh + Power
4. Plug in the USB and downgrade your **personal** chromebook
5. Do the stuff you do to get into your **personal** chromebook
6. Go to Chrome Recovery Utility
7. Erase the drive
8. Now click get started for the recovery utility
9. Enter your **school chromebook's** model name. 
10. Click advanced settings
11. Click Long Term Support
12. Mount the LTS version on your USB
13. Now get your **school** chromebook
14. Downgrade it with the LTS USB
15. Use SH1mmer
16. Profit

**Comment by mmz6** [comment]
Not sure if this works with versions over 112

**Comment by velzie** [comment]
this does absolutely nothing. closing
