### ISSUE TITLE
Error with making dev files

### ISSUE THREAD

**Issue by Josh830-lab** [CoolElectronics/sh1mmer.me#7]
When trying to make a dev file I get this in the WSL terminal:
The file /dev/loop3p13 does not exist and no size was specified.

All packages are installed properly and up to date as well as Ubuntu

**Comment by velzie** [comment]
I'm inclined to believe this is a problem with WSL, not the script itself.
Try restarting WSL / windows and running the script again. If the problem persists you should either use a virtual machine running linux or a liveusb environment.

**Comment by Josh830-lab** [comment]
Alright thanks I'll let you know how it goes

**Comment by Josh830-lab** [comment]
Yep it was a WSL problem
