### ISSUE TITLE
shim server down

### ISSUE THREAD

**Issue by tuta-amb** [CoolElectronics/sh1mmer.me#77]
ok i know that this is against the issues readme, but the server files.ultimatesrv.com and mirror.the-repo.org are both down and don't work, and i can't find the files anywhere else.

**Comment by tuta-amb** [comment]
wdym not planned?

does the server work for you

**Comment by TheMemeSniper** [comment]
you literally said it yourself, this issue is against the readme 🐟

**Comment by tuta-amb** [comment]
well what do i do

**Comment by velzie** [comment]
idk but it's not our problem
