### ISSUE TITLE
Developer Mode is disabled on this device by system policy

### ISSUE THREAD

**Issue by Maxb0tbeep** [CoolElectronics/sh1mmer.me#8]
Is it possible to disable or bypass this? 
![image](https://user-images.githubusercontent.com/55332100/214751208-e8df5c88-460a-4aae-9da5-a9a83915fab3.png)

It fails to boot to the drive when you plug it in because of this

thanks :)

**Comment by velzie** [comment]
Make sure you're following the instructions. You're supposed to see that screen.

**Comment by Maxb0tbeep** [comment]
@CoolElectronics I don't think you understand, read the text at the top.
After plugging the USB stick in, it shows this:
![image](https://user-images.githubusercontent.com/55332100/214758048-c95c7f39-4f72-4c68-8636-fbfb976183cf.jpg)

**Comment by TheMemeSniper** [comment]
> @CoolElectronics I don't think you understand, read the text at the top.
> After plugging the USB stick in, it shows this:
> ![image](https://user-images.githubusercontent.com/55332100/214758048-c95c7f39-4f72-4c68-8636-fbfb976183cf.jpg)
> 

you're booting a recovery image, not a shim.

**Comment by scarat3k** [comment]
lmao skid

**Comment by velzie** [comment]
That isn't sh1mmer, it's a stock recovery image. The code to produce that screen can't be found anywhere in the shims. You downloaded the wrong file, or flashed it to the wrong USB drive.

**Comment by Maxb0tbeep** [comment]
true mb, I got the image from chrome100.dev like the instructions said, what did I do wrong?

**Comment by Maxb0tbeep** [comment]
nevermind I have brain damage and cant fucking read

**Comment by TheMemeSniper** [comment]
🐟

**Comment by Maxb0tbeep** [comment]
fish :)

**Comment by Maxb0tbeep** [comment]
are there any mirrors I can get the shim from?
![image](https://user-images.githubusercontent.com/55332100/214765181-bd8cd075-b97a-49ff-b769-2f5b16e1e544.png)

**Comment by Maxb0tbeep** [comment]
nevermind https://obelous.dev/sh1mmer
