### ISSUE TITLE
whenever i run wax_legacy.sh it doesnt work

### ISSUE THREAD

**Issue by Imzeroo** [CoolElectronics/sh1mmer.me#84]
For some reason every time I run "sudo bash wax_legacy.sh" it gives "wax_legacy.sh: line 143: lib/sfdisk: Permission denied" any help would be much appreciated! 
![image](https://github.com/MercuryWorkshop/sh1mmer/assets/62083589/015dddaa-a3c7-403a-9e98-971fc022337f)

**Comment by velzie** [comment]
chmod +x lib/sfdisk

**Comment by Imzeroo** [comment]
Thanks that helped but now i get "sfdisk: cannot open : No such file or directory"
