### ISSUE TITLE
i get a gpt pmbr size mismatch error when running wax_legacy.sh

### ISSUE THREAD

**Issue by Imzeroo** [CoolElectronics/sh1mmer.me#85]
whenever i run wax_legacy.sh i get "GPT PMBR size mismatch (10400288 != 9425407) will be corrected by write" 
![image](https://github.com/MercuryWorkshop/sh1mmer/assets/62083589/1b1f0bf3-b572-4da4-bec7-92d29cdc04d3)

**Comment by velzie** [comment]
intended
