### ISSUE TITLE
sh1mmer_legacy/factory_install.sh is missing chromeos-tpm-recovery command

### ISSUE THREAD

**Issue by NotDarkn** [CoolElectronics/sh1mmer.me#89]
In https://github.com/MercuryWorkshop/sh1mmer/blob/beautifulworld/wax/sh1mmer_legacy/root/usr/sbin/factory_install.sh, there is a command called:

```
t | T) chromeos-tpm-recovery ;;
```

However when searching for `chromeos-tpm-recovery` near the top, it doesn't exist. This also means that the command won't do anything as it can't call & execute something that doesn't exist, at least from just looking at the script.

I would assume the fix would be as simple as adding the following code near the top of the script:

```
chromeos-tpm-recovery() {
	echo "Executing chromeos-tpm-recovery"
	tpm_manager_client take_ownership
	chromeos-tpm-recovery
	echo "Done"
}
```

However I'm not sure and don't have the time to test at the moment, nor do I wanna boot into Linux right now to keep testing the script. I'll close this issue if this doesn't get reviewed or if I decide to try testing myself.

**Comment by velzie** [comment]
🐟 it's builtin

**Comment by NotDarkn** [comment]
> 🐟 it's builtin

Oh.
