### ISSUE TITLE
sh1mmer won't open when USB drive plugged in

### ISSUE THREAD

**Issue by DVRSTT** [CoolElectronics/sh1mmer.me#9]
I downloaded the octopus shim from [here](https://obelous.dev/sh1mmer/) and flashed it to a USB stick. when I go to the Esc+Refresh+Power screen and plug it in it shows this 
![image](https://user-images.githubusercontent.com/123671050/214931976-ce7079cd-1c94-4190-88c8-6ca01f288ff4.png)
(I just found that Image online I did not take it.)
Did I do this right or am I dumb?

Chromebook specs just in case:
Dell Chromebook 3100
Chrome OS Version 80.0.3987.137
Platform 12739.94.0-20.03.05

I downgraded to v80 from v109 using a recovery USB

**Comment by TheMemeSniper** [comment]
do you have developer mode turned on?

**Comment by ProgrammerIn-wonderland** [comment]
We have tested that specific model, the issue is either your USB is corrupting the kernel partition or you don't have dev mode

**Comment by scarat3k** [comment]
sh1mmer does tend to not like some USBs. i used sh1mmer on my usb broke after like a week

**Comment by 2Epik4u** [comment]
getting same issue on sandisk cruzer 64 gb usb, Lenovo 100e Chromebook 2nd Gen MTK 2

**Comment by lolbird123** [comment]
similar issue on 100e gen 2 ast (grunt board), but slightly different error ("trying to install am unofficial Chrome OS recovery image which does not pass verification").
tried on two different sandisk drives, both 32gb

**Comment by 2Epik4u** [comment]
> similar issue on 100e gen 2 ast (grunt board), but slightly different error ("trying to install am unofficial Chrome OS recovery image which does not pass verification").
> tried on two different sandisk drives, both 32gb

did you download the shim file according to your Chromebook model?

**Comment by lolbird123** [comment]
> > similar issue on 100e gen 2 ast (grunt board), but slightly different error ("trying to install am unofficial Chrome OS recovery image which does not pass verification").
> > tried on two different sandisk drives, both 32gb
> 
> did you download the shim file according to your Chromebook model?

yes, i have a 100e gen 2 ast, which according to both chrome://version and chrome100.dev is a grunt board, and tried both the latest one one chrome100.dev and the one with the version specified on the lenovo driver site for that model

both compiled with wax.sh and flashed fine, but both were rejected by the chromebook
tried each on the two usbs, and tried the recovery trick multiple times on different ports, but always got the same result every time

**Comment by ProgrammerIn-wonderland** [comment]
odd

**Comment by lolbird123** [comment]
i got it to work a while ago, i misread the instructions initially and used a recovery image instead of a shim when compiling

pretty sure im the reason "DO NOT DOWNLOAD ANYTHING FROM CHROME100.DEV AND USE IT WITH THE BUILDER, IT WILL NOT WORK." is in the readme now
