### ISSUE TITLE
wax_legacy.sh: line 139: lib/sfdisk: Permission denied

### ISSUE THREAD

**Issue by NotDarkn** [CoolElectronics/sh1mmer.me#91]
**OS/Distro:**
Debian 12 w/ GNOME 43.6

**Issue:**
Can't use `wax_legacy.sh`.

**Description:**
Using `wax.sh` works just fine without error, however after attempting to use `wax_legacy.sh`, it does the following prompts:
```
Warning: this is a legacy version of wax. There may be unresolved issues
Info: Deleting useless partitions
wax_legacy.sh: line 139: lib/sfdisk: Permission denied
```
Then I'm kicked back into being able to execute commands again in Terminal. Before you call me incompetent, **yes I did run the script as sudo and superuser.**

**Comment by NotDarkn** [comment]
nevermind, solution was running this command:
```
chmod +x lib/sfdisk
```

**Comment by velzie** [comment]
not at my computer rn and you own the code so you can you just add that line

**Comment by BinBashBanana** [comment]
Will do

**Comment by BinBashBanana** [comment]
fixed @NotDarkn

**Comment by NotDarkn** [comment]
> fixed @NotDarkn

nice
