### ISSUE TITLE
ERROR: Cannot find required file: /usr/share/vboot/devkeys/kernel_xxxxx

### ISSUE THREAD

**Issue by NotDarkn** [CoolElectronics/sh1mmer.me#93]
**OS/Distro:**
EndeavourOS w/ GNOME 45.0

**Issue:**
Can't use `wax_legacy.sh` or `wax.sh` due to missing required files.

**Description:**
Using either `wax_legacy.sh` or `.wax.sh` on [EndeavourOS](https://endeavouros.com) (an Arch-based operating system) presents the following errors:
```
ERROR: Cannot find required file: /usr/share/vboot/devkeys/kernel.keyblock
ERROR: Cannot find required file: /usr/share/vboot/devkeys/kernel_data_key.vbprivk
ERROR: Cannot find required file: /usr/share/vboot/devkeys/kernel_subkey.vbpubk
```

<details>
<summary><b>Logs:</b> <kbd>wax.sh</kbd></summary>
<kbd>
[darkn@bobbabook wax]$ sudo bash wax.sh '/home/darkn/Downloads/beautifulworld.bin'<br>
-------------------------------------------------------------------------------------------------------------<br>
Welcome to wax, a shim modifying automation tool made by CoolElectronics and Sharp_Jack, greatly improved by r58playz and Rafflesia<br>
Prerequisites: cgpt must be installed, program must be ran as root, chromebrew.tar.gz needs to exist inside the wax folder<br>
-------------------------------------------------------------------------------------------------------------<br>
Launch flags you should know about: --dev will install a much larger chromebrew partition used for testing, --antiskid will relock the rootfs<br>
Expanding bin for 'arch' partition. this will take a while<br>
4294967296 bytes (4.3 GB, 4.0 GiB) copied, 8 s, 544 MB/s<br>
4+0 records in<br>
4+0 records out<br>
4294967296 bytes (4.3 GB, 4.0 GiB) copied, 7.89748 s, 544 MB/s<br>
<br>
Welcome to fdisk (util-linux 2.39.2).<br>
Changes will remain in memory only, until you decide to write them.<br>
Be careful before using the write command.<br>
<br>
GPT PMBR size mismatch (8575065 != 16963673) will be corrected by write.<br>
The backup GPT table is not on the end of the device. This problem will be corrected by write.<br>
<br>
Command (m for help): <br>
The partition table has been altered.<br>
Syncing disks.<br>
<br>
Partitioning<br>
<br>
Welcome to fdisk (util-linux 2.39.2).<br>
Changes will remain in memory only, until you decide to write them.<br>
Be careful before using the write command.<br>
<br>
<br>
Command (m for help): Partition number (13-128, default 13): First sector (16452-16963640, default 8577024): Last sector, +/-sectors or +/-size{K,M,G,T,P} (8577024-16963640, default 16963583): <br>
Created a new partition 13 of type 'Linux filesystem' and of size 4 GiB.<br>
<br>
Command (m for help): The partition table has been altered.<br>
Syncing disks.<br>
<br>
Creating loop device<br>
Making arch partition<br>
mke2fs 1.47.0 (5-Feb-2023)<br>
Discarding device blocks: done<br>                         
Creating filesystem with 1048320 4k blocks and 262144 inodes<br>
Filesystem UUID: 787928ed-acaa-4e4d-9d32-364bbcb3f3d9<br>
Superblock backups stored on blocks: <br>
	32768, 98304, 163840, 229376, 294912, 819200, 884736<br>
<br>
Allocating group tables: done<br>                            
Writing inode tables: done<br>                            
Writing superblocks and filesystem accounting information: done<br> 
<br>
Making ROOT mountable<br>
ERROR: Cannot find required file: /usr/share/vboot/devkeys/kernel.keyblock<br>
ERROR: Cannot find required file: /usr/share/vboot/devkeys/kernel_data_key.vbprivk<br>
ERROR: Cannot find required file: /usr/share/vboot/devkeys/kernel_subkey.vbpubk<br>
[darkn@bobbabook wax]$ 
</kbd>
</details>

<details>
<summary><b>Logs:</b> <kbd>wax_legacy.sh</kbd></summary>
<kbd>
[darkn@bobbabook wax]$ sudo bash wax_legacy.sh '/home/darkn/Downloads/legacy.bin'<br>
-------------------------------------------------------------------------------------------------------------<br>
Welcome to wax, a shim modifying automation tool<br>
Credits: CoolElectronics, Sharp_Jack, r58playz, Rafflesia, OlyB<br>
Prerequisites: cgpt must be installed, program must be ran as root<br>
-------------------------------------------------------------------------------------------------------------<br>
Warning: this is a legacy version of wax. There may be unresolved issues<br>
Info: Deleting useless partitions<br>
<br>
The partition table has been altered.<br>
Syncing disks.<br>
Info: Creating loop device<br>
Info: Making ROOT mountable<br>
ERROR: Cannot find required file: /usr/share/vboot/devkeys/kernel.keyblock<br>
ERROR: Cannot find required file: /usr/share/vboot/devkeys/kernel_data_key.vbprivk<br>
ERROR: Cannot find required file: /usr/share/vboot/devkeys/kernel_subkey.vbpubk<br>
[darkn@bobbabook wax]$ 
</details>

**Notes:**
- Yes, I ran the command as sudo.
- Yes, I've tried using superuser.
- Yes, I have `cgpt`, `git`, and `wget`, all installed.
- Yes, I'm using a working RMA shim, it's from [dl.osu.bio](https://dl.osu.bio).
- Yes, this used to work on Debian.
- After the command fails, you aren't able to use the same .bin anymore and you need to extract it again from the .zip.

**Comment by NotDarkn** [comment]
asked another friend of mine to try building an image on an Arch-based OS and they also had the same error. so either it's an issue with Arch or the scripts having an issue with an Arch-based OS

**Comment by kxtzownsu** [comment]
Do you have `aur/vboot-utils` installed?

**Comment by BinBashBanana** [comment]
assign me

**Comment by BinBashBanana** [comment]
wow I assigned myself

**Comment by NotDarkn** [comment]
> Do you have `aur/vboot-utils` installed?

yes

**Comment by kxtzownsu** [comment]
> > Do you have `aur/vboot-utils` installed?
> 
> yes

Does this issue still occur?
Check if the files are there, if they arent try re-installing the package

**Comment by kxtzownsu** [comment]
> wow I assigned myself

crazy

**Comment by NotDarkn** [comment]
> > > Do you have `aur/vboot-utils` installed?
> > 
> > 
> > yes
> 
> Does this issue still occur? Check if the files are there, if they arent try re-installing the package

reinstalled `vboot-utils` and now it works, fuck.

**Comment by kxtzownsu** [comment]
lol

**Comment by BinBashBanana** [comment]
this shouldn't happen anymore as of latest commit
