### ISSUE TITLE
sfdisk: [rmashim.bin] partition 10: failed to delete

### ISSUE THREAD

**Issue by NotDarkn** [CoolElectronics/sh1mmer.me#94]
**OS/Distro:**
EndeavourOS w/ GNOME 45.0

**Issue:**
Can't use `wax_legacy.sh` with BRASK, BRYA, CORSOLA, or REKS.

**Description:**
Using `wax_legacy.sh` with BRASK, BRYA, CORSOLA, OR REKS, on [EndeavourOS](https://endeavouros.com) (an Arch-based operating system) presents the following log/error:
```
Info: Deleting useless partitions
sfdisk: brask.bin: partition 10: failed to delete
```
<details>
<summary><b>Logs:</b> <kbd>brask.bin</kbd></summary>
<kbd>
[darkn@bobbabook wax]$ sudo bash wax_legacy.sh '/home/darkn/Downloads/brask.bin'<br>
-------------------------------------------------------------------------------------------------------------<br>
Welcome to wax, a shim modifying automation tool<br>
Credits: CoolElectronics, Sharp_Jack, r58playz, Rafflesia, OlyB<br>
Prerequisites: e2fsprogs must be installed, program must be ran as root<br>
Warning: this is a legacy version of wax. There may be unresolved issues<br>
-------------------------------------------------------------------------------------------------------------<br>
Info: Deleting useless partitions<br>
sfdisk: /home/darkn/Downloads/brask.bin: partition 10: failed to delete<br>
[darkn@bobbabook wax]$ 
</kbd>
</details>

<details>
<summary><b>Logs:</b> <kbd>brya.bin</kbd></summary>
<kbd>
[darkn@bobbabook wax]$ sudo bash wax_legacy.sh '/home/darkn/Downloads/brya.bin'<br>
-------------------------------------------------------------------------------------------------------------<br>
Welcome to wax, a shim modifying automation tool<br>
Credits: CoolElectronics, Sharp_Jack, r58playz, Rafflesia, OlyB<br>
Prerequisites: e2fsprogs must be installed, program must be ran as root<br>
Warning: this is a legacy version of wax. There may be unresolved issues<br>
-------------------------------------------------------------------------------------------------------------<br>
Info: Deleting useless partitions<br>
sfdisk: /home/darkn/Downloads/brya.bin: partition 10: failed to delete<br>
[darkn@bobbabook wax]$
</kbd>
</details>

<details>
<summary><b>Logs:</b> <kbd>corsola.bin</kbd></summary>
<kbd>
[darkn@bobbabook wax]$ sudo bash wax_legacy.sh '/home/darkn/Downloads/corsola.bin'<br>
-------------------------------------------------------------------------------------------------------------<br>
Welcome to wax, a shim modifying automation tool<br>
Credits: CoolElectronics, Sharp_Jack, r58playz, Rafflesia, OlyB<br>
Prerequisites: e2fsprogs must be installed, program must be ran as root<br>
Warning: this is a legacy version of wax. There may be unresolved issues<br>
-------------------------------------------------------------------------------------------------------------<br>
Info: Deleting useless partitions<br>
sfdisk: /home/darkn/Downloads/corsola.bin: partition 10: failed to delete<br>
[darkn@bobbabook wax]$ 
</kbd>
</details>

<details>
<summary><b>Logs:</b> <kbd>reks.bin</kbd></summary>
<kbd>
[darkn@bobbabook wax]$ sudo bash wax_legacy.sh '/home/darkn/Downloads/reks.bin'<br>
-------------------------------------------------------------------------------------------------------------<br>
Welcome to wax, a shim modifying automation tool<br>
Credits: CoolElectronics, Sharp_Jack, r58playz, Rafflesia, OlyB<br>
Prerequisites: e2fsprogs must be installed, program must be ran as root<br>
Warning: this is a legacy version of wax. There may be unresolved issues<br>
-------------------------------------------------------------------------------------------------------------<br>
Info: Deleting useless partitions<br>
GPT PMBR size mismatch (10269216 != 8393494) will be corrected by write.<br>
sfdisk: /home/darkn/Downloads/reks.bin: partition 4: failed to delete<br>
[darkn@bobbabook wax]$ 
</kbd>
</details>

**Notes:**
- Yes, I ran the command as sudo.
- Yes, I've tried using superuser.
- Yes, I have `cgpt`, `git`, and `wget`, all installed.
- Yes, I'm using a working RMA shim, it's from [dl.osu.bio](https://dl.osu.bio).

**Comment by NotDarkn** [comment]
assign @BinBashBanana because he said he plans on fixing it soon
![image](https://github.com/MercuryWorkshop/sh1mmer/assets/73033672/f705a306-e561-402b-818d-7eeb1f7ae221)

**Comment by BinBashBanana** [comment]
This should be fixed now, tested on brask, dedede, octopus, reks, and volteer.
