### ISSUE TITLE
Compiling a shim is causing issues in both WSL2 Debian and in a VM of Debian (presumably because of the fix for issue #94)

### ISSUE THREAD

**Issue by huaraina** [CoolElectronics/sh1mmer.me#96]
Title says most of it.
![image](https://github.com/MercuryWorkshop/sh1mmer/assets/95729626/1a03c258-43cd-4f9b-8d59-3601ba38d25c)
Image shows the error in question. 
Potential causes could be WSL2 just being WSL or the vm using a symlink like thing to my windows machine. 
Not sure if it's too bad but it has made it impossible for me to compile.
Line with the error: ![image](https://github.com/MercuryWorkshop/sh1mmer/assets/95729626/d1bd4edb-a2da-45d6-b235-e252190a7eba)
I know we aren't supposed to report WSL issues but this might not necessarily be WSL.
I'm gonna try to use the previous version of the file just in case.

**Comment by velzie** [comment]
it's wsl

**Comment by huaraina** [comment]
It happened outside of WSL...

**Comment by velzie** [comment]
yes, wsl issue

**Comment by velzie** [comment]
(also know the difference between bash and sh, etc)

**Comment by huaraina** [comment]
oh wait that was the issue oops

**Comment by BinBashBanana** [comment]
it won't run without bash now @huaraina
