### ISSUE TITLE
Error: Factory installation aborted.

### ISSUE THREAD

**Issue by Alriceee** [CoolElectronics/sh1mmer.me#98]
```
ERROR: Factory installation aborted.
Dumping dmesg to /log
Saving log files from: /log -> /dev/sda1 factory_shim_logs
Failures seen trying to save log file. 
To debug, add [cros_debug] to your kernel command line.
```

Any help with this?

**Comment by Alriceee** [comment]
**had to use the legacy builder. im on a lenovo 100e chromebook (board name ROBO) with x86_64 architecture.

**Comment by velzie** [comment]
corrupted usb, bad connection, unplugged during the process, etc

there are about 20 duplicates of this, please look at the others before making one

**Comment by Alriceee** [comment]
still getting same error (don't come at me with skill issue, i already know.) i tried 4 different usb devices, could it be the port or something. @CoolElectronics (not sorry for ping)

**Comment by NotDarkn** [comment]
you have a bad shim, please re-download the shim and build it again
